services:
  eventmap-fastapi:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    container_name: backend
    networks:
      - eventmap

  eventmap-frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    container_name: frontend
    environment:
      - API_URL=http://backend:8000/
    networks:
      - eventmap

networks:
  eventmap:
    driver: bridge
